services:
  nginx:
    build: ./proxy
    image: proxy
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/frontend:/usr/share/nginx/html
    restart: always

  backend-user:
    build: ./backend-user
    image: backend-user
    container_name: backend-user
    environment:
      - OAUTH_UID_42=${OAUTH_UID_42}
      - OAUTH_SECRET_42=${OAUTH_SECRET_42}
      - OAUTH_REDIRECT_42=${OAUTH_REDIRECT_42}
    ports:
      - "8000:8000"
    volumes:
      - ${PWD}/backend-user:/app
    restart: always
