services:
  nginx:
    build: ./proxy
    image: proxy
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/frontend:/usr/share/nginx/html

  backend-user:
    build: ./backend-user
    image: backend-user
    container_name: backend-user
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/backend-user:/app
      - /app/node_modules
    environment:
      - OAUTH_UID_42=${OAUTH_UID_42}
      - OAUTH_SECRET_42=${OAUTH_SECRET_42}
      - OAUTH_REDIRECT_42=${OAUTH_REDIRECT_42}
      - OAUTH_UID_GITHUB=${OAUTH_UID_GITHUB}
      - OAUTH_SECRET_GITHUB=${OAUTH_SECRET_GITHUB}
      - OAUTH_REDIRECT_GITHUB=${OAUTH_REDIRECT_GITHUB}
      - DATABASE_URL=${DATABASE_URL}
    tty: true

  backend-ping-pong:
    build: ./backend-ping-pong
    image: backend-ping-pong
    container_name: backend-ping-pong
    ports:
      - "3001:3000"
    volumes:
      - ${PWD}/backend-ping-pong:/app
      - /app/node_modules
    environment:
      - AMQP_URL=${AMQP_URL}
    depends_on:
      - rabbitmq
    tty: true

  backend-blockchain:
    build: ./backend-blockchain
    image: backend-blockchain
    container_name: backend-blockchain
    ports:
      - "3002:3000"
    volumes:
      - ${PWD}/backend-blockchain:/app
      - /app/node_modules
    environment:
      - AMQP_URL=${AMQP_URL}
    depends_on:
      - rabbitmq
    tty: true

  rabbitmq:
    image: rabbitmq:4.0-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
    volumes:
      - ${PWD}/backend-blockchain:/app
      - /app/node_modules
    tty: true

  frontend:
    build: ./frontend
    image: frontend
    container_name: frontend
    volumes:
      - ${PWD}/frontend:/app
      - /app/node_modules
    tty: true