services:
  nginx:
    build: ./proxy
    image: proxy
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - proxy-log:/var/log/nginx
      - ${PWD}/frontend:/usr/share/nginx/html

  backend-user:
    build: ./backend-user
    image: backend-user
    container_name: backend-user
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/backend-user:/app
      - /app/node_modules
    environment:
      - OAUTH_UID_42=${OAUTH_UID_42}
      - OAUTH_SECRET_42=${OAUTH_SECRET_42}
      - OAUTH_REDIRECT_42=${OAUTH_REDIRECT_42}
      - OAUTH_UID_GITHUB=${OAUTH_UID_GITHUB}
      - OAUTH_SECRET_GITHUB=${OAUTH_SECRET_GITHUB}
      - OAUTH_REDIRECT_GITHUB=${OAUTH_REDIRECT_GITHUB}
    tty: true

  backend-ping-pong:
    build: ./backend-ping-pong
    image: backend-ping-pong
    container_name: backend-ping-pong
    ports:
      - "3001:3000"
    volumes:
      - ${PWD}/backend-ping-pong:/app
      - /app/node_modules
    tty: true

  logstash:
    image: docker.elastic.co/logstash/logstash:8.17.2
    container_name: logstash
    volumes:
      - ${PWD}/elk/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ${PWD}/elk/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - proxy-log:/var/log/nginx
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    tty: true

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.2
    container_name: kibana
    ports:
      - "5601:5601"
    # volumes:
      # - ${PWD}/elk/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml

volumes:
  proxy-log:
