services:
  nginx:
    build: ./proxy
    image: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ${PWD}/frontend:/usr/share/nginx/html
    restart: always

  backend-user:
    build: ./backend-user
    image: backend-user
    container_name: backend-user
    ports:
      - "8000:8000"
    volumes:
      - ${PWD}/backend-user:/app
    restart: always
