services:
  nginx:
    build: ./proxy
    image: proxy
    container_name: proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - proxy-log:/var/log/nginx
      - ${PWD}/frontend:/usr/share/nginx/html
    depends_on:
      frontend:
        condition: service_healthy
      backend-user:
        condition: service_healthy
      backend-ping-pong:
        condition: service_healthy
      backend-blockchain:
        condition: service_healthy

  frontend:
    build: ./frontend
    image: frontend
    container_name: frontend
    volumes:
      - ${PWD}/frontend:/app
      - /app/node_modules
    healthcheck:
      test: wget -qO- http://frontend:5173/
      interval: 10s
      timeout: 10s
      retries: 5
    tty: true

  backend-user:
    build: ./backend-user
    image: backend-user
    container_name: backend-user
    ports:
      - "3000:3000"
    volumes:
      - ${PWD}/backend-user:/app
      - /app/node_modules
    environment:
      - OAUTH_UID_42=${OAUTH_UID_42}
      - OAUTH_SECRET_42=${OAUTH_SECRET_42}
      - OAUTH_REDIRECT_42=${OAUTH_REDIRECT_42}
      - OAUTH_UID_GITHUB=${OAUTH_UID_GITHUB}
      - OAUTH_SECRET_GITHUB=${OAUTH_SECRET_GITHUB}
      - OAUTH_REDIRECT_GITHUB=${OAUTH_REDIRECT_GITHUB}
      - DATABASE_URL=${DATABASE_URL}
    healthcheck:
      test: wget -qO- http://localhost:3000/healthcheck
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      rabbitmq:
        condition: service_healthy
    tty: true

  backend-ping-pong:
    build: ./backend-ping-pong
    image: backend-ping-pong
    container_name: backend-ping-pong
    ports:
      - "3001:3000"
    volumes:
      - ${PWD}/backend-ping-pong:/app
      - /app/node_modules
    environment:
      - AMQP_URL=${AMQP_URL}
    healthcheck:
      test: wget -qO- http://localhost:3000/healthcheck
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      rabbitmq:
        condition: service_healthy
    tty: true

  backend-blockchain:
    build: ./backend-blockchain
    image: backend-blockchain
    container_name: backend-blockchain
    ports:
      - "3002:3000"
    volumes:
      - ${PWD}/backend-blockchain:/app
      - /app/node_modules
    environment:
      - AMQP_URL=${AMQP_URL}
    healthcheck:
      test: wget -qO- http://localhost:3000/healthcheck
      interval: 10s
      timeout: 10s
      retries: 5
    depends_on:
      rabbitmq:
        condition: service_healthy
    tty: true

  rabbitmq:
    image: rabbitmq:4.0-alpine
    container_name: rabbitmq
    ports:
      - "5672:5672"
    volumes:
      - ${PWD}/backend-blockchain:/app
      - /app/node_modules
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 10s
      retries: 5
    tty: true

  logstash:
    image: docker.elastic.co/logstash/logstash:8.17.2
    container_name: logstash
    volumes:
      - ${PWD}/elk/logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf
      - ${PWD}/elk/logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
      - proxy-log:/var/log/nginx
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    depends_on:
      elasticsearch:
        condition: service_healthy
    tty: true

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.17.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
    healthcheck:
      test: [ "CMD", "curl", "-k", "https://localhost:9200" ]
      interval: 30s
      timeout: 10s
      retries: 5

  kibana:
    image: docker.elastic.co/kibana/kibana:8.17.2
    container_name: kibana
    ports:
      - "5601:5601"
    volumes:
      - ${PWD}/elk/kibana/kibana.yml:/usr/share/kibana/config/kibana.yml
      - ${PWD}/elk/kibana//docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh:ro
      - ${PWD}/elk/kibana/dashboard-proxy.ndjson:/elk/kibana/dashboard-proxy.ndjson:ro
    environment:
      - ELASTICSEARCH_HOSTS=https://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=kibana_system
      - ELASTICSEARCH_PASSWORD=kibana
      - ELASTICSEARCH_SSL_VERIFICATIONMODE=none
    depends_on:
      elasticsearch:
        condition: service_healthy
    entrypoint: [ "/usr/local/bin/docker-entrypoint.sh" ]

volumes:
  proxy-log:
